/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAccessiRouteImport } from './routes/_authenticated/accessi'
import { Route as AuthenticatedAllenamentoRouteImport } from './routes/_authenticated/allenamento'
import { Route as AuthenticatedAreaRouteImport } from './routes/_authenticated/area'
import { Route as AuthenticatedCatalogoObiettiviRouteImport } from './routes/_authenticated/catalogo-obiettivi'
import { Route as AuthenticatedClientiRouteImport } from './routes/_authenticated/clienti'
import { Route as AuthenticatedEserciziRouteImport } from './routes/_authenticated/esercizi'
import { Route as AuthenticatedObiettiviRouteImport } from './routes/_authenticated/obiettivi'
import { Route as AuthenticatedRegistrazioniRouteImport } from './routes/_authenticated/registrazioni'
import { Route as AuthenticatedSchedaRouteImport } from './routes/_authenticated/scheda'
import { Route as AuthenticatedStoricoRouteImport } from './routes/_authenticated/storico'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccessiRoute = AuthenticatedAccessiRouteImport.update({
  id: '/accessi',
  path: '/accessi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAllenamentoRoute =
  AuthenticatedAllenamentoRouteImport.update({
    id: '/allenamento',
    path: '/allenamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAreaRoute = AuthenticatedAreaRouteImport.update({
  id: '/area',
  path: '/area',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogoObiettiviRoute =
  AuthenticatedCatalogoObiettiviRouteImport.update({
    id: '/catalogo-obiettivi',
    path: '/catalogo-obiettivi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientiRoute = AuthenticatedClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEserciziRoute = AuthenticatedEserciziRouteImport.update({
  id: '/esercizi',
  path: '/esercizi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObiettiviRoute = AuthenticatedObiettiviRouteImport.update({
  id: '/obiettivi',
  path: '/obiettivi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistrazioniRoute =
  AuthenticatedRegistrazioniRouteImport.update({
    id: '/registrazioni',
    path: '/registrazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedaRoute = AuthenticatedSchedaRouteImport.update({
  id: '/scheda',
  path: '/scheda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoricoRoute = AuthenticatedStoricoRouteImport.update({
  id: '/storico',
  path: '/storico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessi': typeof AuthenticatedAccessiRoute
  '/allenamento': typeof AuthenticatedAllenamentoRoute
  '/area': typeof AuthenticatedAreaRoute
  '/catalogo-obiettivi': typeof AuthenticatedCatalogoObiettiviRoute
  '/clienti': typeof AuthenticatedClientiRoute
  '/esercizi': typeof AuthenticatedEserciziRoute
  '/obiettivi': typeof AuthenticatedObiettiviRoute
  '/registrazioni': typeof AuthenticatedRegistrazioniRoute
  '/scheda': typeof AuthenticatedSchedaRoute
  '/storico': typeof AuthenticatedStoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessi': typeof AuthenticatedAccessiRoute
  '/allenamento': typeof AuthenticatedAllenamentoRoute
  '/area': typeof AuthenticatedAreaRoute
  '/catalogo-obiettivi': typeof AuthenticatedCatalogoObiettiviRoute
  '/clienti': typeof AuthenticatedClientiRoute
  '/esercizi': typeof AuthenticatedEserciziRoute
  '/obiettivi': typeof AuthenticatedObiettiviRoute
  '/registrazioni': typeof AuthenticatedRegistrazioniRoute
  '/scheda': typeof AuthenticatedSchedaRoute
  '/storico': typeof AuthenticatedStoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/accessi': typeof AuthenticatedAccessiRoute
  '/_authenticated/allenamento': typeof AuthenticatedAllenamentoRoute
  '/_authenticated/area': typeof AuthenticatedAreaRoute
  '/_authenticated/catalogo-obiettivi': typeof AuthenticatedCatalogoObiettiviRoute
  '/_authenticated/clienti': typeof AuthenticatedClientiRoute
  '/_authenticated/esercizi': typeof AuthenticatedEserciziRoute
  '/_authenticated/obiettivi': typeof AuthenticatedObiettiviRoute
  '/_authenticated/registrazioni': typeof AuthenticatedRegistrazioniRoute
  '/_authenticated/scheda': typeof AuthenticatedSchedaRoute
  '/_authenticated/storico': typeof AuthenticatedStoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessi'
    | '/allenamento'
    | '/area'
    | '/catalogo-obiettivi'
    | '/clienti'
    | '/esercizi'
    | '/obiettivi'
    | '/registrazioni'
    | '/scheda'
    | '/storico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessi'
    | '/allenamento'
    | '/area'
    | '/catalogo-obiettivi'
    | '/clienti'
    | '/esercizi'
    | '/obiettivi'
    | '/registrazioni'
    | '/scheda'
    | '/storico'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/accessi'
    | '/_authenticated/allenamento'
    | '/_authenticated/area'
    | '/_authenticated/catalogo-obiettivi'
    | '/_authenticated/clienti'
    | '/_authenticated/esercizi'
    | '/_authenticated/obiettivi'
    | '/_authenticated/registrazioni'
    | '/_authenticated/scheda'
    | '/_authenticated/storico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accessi': {
      id: '/_authenticated/accessi'
      path: '/accessi'
      fullPath: '/accessi'
      preLoaderRoute: typeof AuthenticatedAccessiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/allenamento': {
      id: '/_authenticated/allenamento'
      path: '/allenamento'
      fullPath: '/allenamento'
      preLoaderRoute: typeof AuthenticatedAllenamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/area': {
      id: '/_authenticated/area'
      path: '/area'
      fullPath: '/area'
      preLoaderRoute: typeof AuthenticatedAreaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogo-obiettivi': {
      id: '/_authenticated/catalogo-obiettivi'
      path: '/catalogo-obiettivi'
      fullPath: '/catalogo-obiettivi'
      preLoaderRoute: typeof AuthenticatedCatalogoObiettiviRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clienti': {
      id: '/_authenticated/clienti'
      path: '/clienti'
      fullPath: '/clienti'
      preLoaderRoute: typeof AuthenticatedClientiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/esercizi': {
      id: '/_authenticated/esercizi'
      path: '/esercizi'
      fullPath: '/esercizi'
      preLoaderRoute: typeof AuthenticatedEserciziRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obiettivi': {
      id: '/_authenticated/obiettivi'
      path: '/obiettivi'
      fullPath: '/obiettivi'
      preLoaderRoute: typeof AuthenticatedObiettiviRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registrazioni': {
      id: '/_authenticated/registrazioni'
      path: '/registrazioni'
      fullPath: '/registrazioni'
      preLoaderRoute: typeof AuthenticatedRegistrazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheda': {
      id: '/_authenticated/scheda'
      path: '/scheda'
      fullPath: '/scheda'
      preLoaderRoute: typeof AuthenticatedSchedaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storico': {
      id: '/_authenticated/storico'
      path: '/storico'
      fullPath: '/storico'
      preLoaderRoute: typeof AuthenticatedStoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessiRoute: typeof AuthenticatedAccessiRoute
  AuthenticatedAllenamentoRoute: typeof AuthenticatedAllenamentoRoute
  AuthenticatedAreaRoute: typeof AuthenticatedAreaRoute
  AuthenticatedCatalogoObiettiviRoute: typeof AuthenticatedCatalogoObiettiviRoute
  AuthenticatedClientiRoute: typeof AuthenticatedClientiRoute
  AuthenticatedEserciziRoute: typeof AuthenticatedEserciziRoute
  AuthenticatedObiettiviRoute: typeof AuthenticatedObiettiviRoute
  AuthenticatedRegistrazioniRoute: typeof AuthenticatedRegistrazioniRoute
  AuthenticatedSchedaRoute: typeof AuthenticatedSchedaRoute
  AuthenticatedStoricoRoute: typeof AuthenticatedStoricoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessiRoute: AuthenticatedAccessiRoute,
  AuthenticatedAllenamentoRoute: AuthenticatedAllenamentoRoute,
  AuthenticatedAreaRoute: AuthenticatedAreaRoute,
  AuthenticatedCatalogoObiettiviRoute: AuthenticatedCatalogoObiettiviRoute,
  AuthenticatedClientiRoute: AuthenticatedClientiRoute,
  AuthenticatedEserciziRoute: AuthenticatedEserciziRoute,
  AuthenticatedObiettiviRoute: AuthenticatedObiettiviRoute,
  AuthenticatedRegistrazioniRoute: AuthenticatedRegistrazioniRoute,
  AuthenticatedSchedaRoute: AuthenticatedSchedaRoute,
  AuthenticatedStoricoRoute: AuthenticatedStoricoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
